### ISSUE TITLE
Sound plays when vanilla tweaks' data pack Armoured Elytra is active

### ISSUE THREAD

**Issue by BEMZ01** [InsomniaKitten/ArmorSoundTweak#9] opened 2022-05-15 14:07 UTC
Sound spam is played when the Vanilla tweaks data pack Armoured Elytra is installed from https://vanillatweaks.net/picker/datapacks/
Add an option to config to maybe check for a rapid change between chest plate and elytra?

**Comment by DarianLStephens** [comment] 2022-05-15 15:45
It'd be nice if there was any detection for the same item changing, because even taking damage with the inventory open will make the sound play. This is especially annoying with mods having constantly-updating things, like recharging/draining armor.

**Comment by BEMZ01** [comment] 2022-05-15 15:46
maybe integrate with Mod Menu and add a easy to edit config?

**Comment by ChloeDawn** [comment] 2022-05-24 18:21
> maybe integrate with Mod Menu and add a easy to edit config?

Please use a separate ticket for feature requests

**Comment by ChloeDawn** [comment] 2022-05-24 18:22
Duplicate of #7

**Closed as completed by ChloeDawn** 2022-05-24 18:22 UTC
Labels: bug, duplicate
